### ISSUE TITLE
[Remoto] Junior/Mid Backend Developer @YellowIpe

### ISSUE THREAD

**Issue by YellowIpe** [backend-pt/vagas#116]
### Nossa empresa

Temos a missão de inspirar a conexão da tecnologia com as pessoas, fomentamos o melhor de nossos profissionais através de nossa expertise em encontrar e atrair os melhores talentos para os melhores projetos. O Foco nas Pessoas, Colaboração e Comprometimento são os pilares que nos guiam nessa trajetória.

### Descrição da vaga

A YellowIpe está a recrutar programador Backend para integração direta numa empresa nacional.
Nesta posição, procuramos um desenvolvedor de back-end analítico e orientado a resultados que trabalhará com os membros da equipe para solucionar problemas e melhorar os aplicativos e processos de back-end atuais.
O desenvolvedor de back-end usará seu conhecimento de linguagens de programação e ferramentas para analisar códigos atuais e desenvolvimentos do setor, formular processos mais eficientes, resolver problemas e criar uma experiência mais integrada para os usuários.
Você deve ter excelentes habilidades de comunicação, informática e gerenciamento de projetos.
Para ter sucesso como desenvolvedor back-end, você deve se concentrar na construção de um programa melhor e mais eficiente e na criação de uma melhor experiência para o usuário final.
Você deve ser bem informado, colaborativo e motivado.

### Local

Remoto

#### Obrigatórios:

Licenciatura em programação de computadores, ciências da computação ou áreas afins;
Experiência comprovada de trabalho como Desenvolvedor Backend;
É necessária compreensão de linguagens específicas, como TypeScript/JavaScript, HTML, CSS, React e React Native, e sistemas operacionais;
Forte entendimento do ciclo de desenvolvimento de Integração Contínua e Implantação (CI/CD, GitHub Actions) e técnicas e ferramentas de programação;
Forte conhecimento da tecnologia NodeJS, módulos NPM e outras ferramentas;
Forte conhecimento de bancos de dados MongoDB, scripts e manutenção;
Forte conhecimento dos processos e ferramentas do Google Cloud Platform;
Foco em eficiência, experiência do usuário e melhoria de processos;
Capacidade de trabalhar de forma independente ou em grupo;

### Benefícios

- Plano de saúde
- Seguro de vida

### Contratação

CTI

### Como se candidatar

Candidate-se para essa oportunidade enviando o seu CV para: recrutamento@yellowipe.io com a Referencia: "BackEnd Portugal"

### Tempo médio de feedbacks

10 Dias

### Alocação

- [ ] Alocado
- [X] Remoto
- [ ] Presencial
- [ ] Híbrido

### Regime

- [X] Contrato
- [ ] Freela
- [X] RV

### Nível

- [X] Júnior
- [X] Pleno
- [ ] Sênior
- [ ] Especialista

### Período

- [X] Full time
- [ ] Part Time
- [ ] Projeto

### Remuneração

€ 1k - € 2k

**Comment by Matheusfbio** [comment]
Enviado
