### ISSUE TITLE
[Remoto] DevOps - ília Digital

### ISSUE THREAD

**Issue by claumenezes** [backend-pt/vagas#8]
**Why work for us:**
You will have the opportunity to do work that impacts people's lives. It's a chance to solve real problems, with a variety of challenges that will bring growth to you and your career.
We have a friendly, supportive, and adventurous environment. Here, everyone walks side by side. Making mistakes, learning, and evolving together is intrinsic to our culture.
We like to work with different people. Here you will live with people from diverse backgrounds, experiences, skills and perspectives.
At ília, everyone has the same opportunities to grow, and everyone shares a common goal: to make the amazing world simpler.

**About the position:**
By embracing a DevOps culture in conjunction with DevOps practices and tools, teams unlock the magic to better respond to customer needs, to make their applications more reliable, and to work with quality and effectiveness.The biggest challenge of DevOps today is to maintain the balance between the evolution of technology and people. Thus, the concept of quality DevOps necessarily involve reviewing all the practices adopted in the environment in which we are used to working in order to make these practices better, leaner and also more efficient.

**We're looking for someone with:**

- Experience with Backend Development (any language, preferably NodeJS)
- CI/CD Pipelines Implementation
- Experience with Cloud Environments (AWS/Azure)
- Containerization (Docker)
- Advanced / Fluent English or Spanish (Writing and Speaking)
- What could make you stand out:
- Kubernetes experience
- Experience with IaC (Infrastructure as code)
- Monitoring Tools (Grafana, Prometheusm, EFK, etc)
- Hashicorp stack (Terraform, consul, vault, etc)
- Experience with agile teams
- Configuration Managements (Ansible, Puppet, etc)
- Mobile CI/CD

**Benefits:**

- CLT Labor contract (Brazil) - 40h per week with flexible working hours and remote position;
- Medical and Dental Assistance extendable to dependents;
- Food voucher;
- Life insurance;
- Program to encourage the learning of other languages, with mentoring activities and on the Go Fluent platform;
- Award program for referring other professionals;
- Technical Forums: Here we share ideas that deserve to be disseminated for the team's constant development;
- Chapter Groups: Brings together people with similar skills to share ideas, practices and experiences;
- Your Birthday has a cake!
- Byod: It is a program for those who would like to use their own machine.

If you are interested, [click here:](https://boards.greenhouse.io/ilia/jobs/4008888004)

If you need more details, please reach me out on [Linkedin ](https://www.linkedin.com/in/claudia-menezes/)

**Comment by douglasz1** [comment]
Wow gimme spot tho 🙂
