### ISSUE TITLE
[Porto] Java Technical Lead na Mindera

### ISSUE THREAD

**Issue by letiveiga** [backend-pt/vagas#85]
## Descrição da vaga

At Mindera we are building a world class team and would love it for you to join us. You will be part of team working on the premier destination for sports fans online and as a Backend Technical Lead your main focus will be the facilitation and collaboration in the development of usable, performant, accessible, and maintainable web applications with a focus on a delightful user experience.

You will own the build of fully responsive web applications, highly-available around the world, while influencing architecture and technical direction.

You’ll get to help design and evolve the architecture of our webapps and to be part of the journey of continuous improvement to make the team the best that it can be. Your code will be used by thousands of customers worldwide.

National and international expected traveling time varies according to project/client and organisational needs: 0%-15% estimated.

## Local

Remote or Office or Hybrid, your choice! Our offices are in Porto, Aveiro and Coimbra.

## Benefícios

- Health Insurance, because health comes first
- Flexible working hours
- Open holidays, take the time you need for yourself
- Profit distribution for everyone
- Mindera Annual Trip, Sports, and sharing groups to connect and have fun!
- Training & conferences, create your own training plan
- Child Care vouchers

#### Diferenciais

- Choose Laptop & Peripherals that best suit your needs
- Hotspot with unlimited usage (PT), for work or Netflix ;)
- We have amazing offices in Porto, Aveiro, and Coimbra if you want to physically connect with minders. Remote is also an option.
- At the offices, we have a wide range of snacks to keep you fed and healthy
- Partnerships with local businesses

## Requisitos

- 6+ years of software engineering experience; bonus points for previous experience as a tech lead;
- In-depth knowledge of the web tech stack, from DNS to HTTP and client-side technologies;
- Service-oriented architectures, design patterns, and data structures;
- Test automation, continuous integration, and continuous delivery;
- Operational aspects, building performant applications and monitoring them showing you care about your code;
- Working with frameworks such as Spring Boot or Vert.x (although not essential);
- You have an inclusive development mindset and do your best to ensure web applications are usable by anyone, regardless of any disabilities;
- You care about security, use defensive programming and know how to prevent and mitigate common web attack vectors;
- Experience of developing and running large scale production environments in or closely with DevOps / SRE;
- Experience with CI/CD workflows and writing automated tests;
- Experience of agile development practices, i.e. Scrum & Kanban;
- Ability to diagnose problems at any level (Client, HTTP/Network, Server, OS);
- You recognise the value of code reviews and have experience in mentoring teammates while helping them grow.

## Contratação

Full-time

## Nossa empresa

At Mindera we use technology to build products we are proud of, with people we love 💛

Software Engineering Applications, including Web and Mobile, are at the core of what we do at Mindera 💻

We partner with our clients, to understand their products and deliver high-performance, resilient, and scalable software systems that create an impact on their users and businesses across the world 🌐

You get to work with a bunch of great people, where the whole team owns the project together 🚀

Our culture reflects our lean and self-management attitude. We encourage our colleagues to take risks, make decisions, work in a collaborative way and talk to everyone to enhance communication 🧭

We are proud of our work and we love to learn all and everything while navigating through an Agile, Lean and collaborative environment ⭐

Check out our [Blog](http://mindera.com/blog) and our [Handbook](http://bit.ly/MinderaHandbook)!

Our offices are located: Porto, Aveiro, Coimbra - Portugal 🇵🇹 | Leicester - UK 🇬🇧 | San Diego, San Francisco - USA 🇺🇸 | Chennai, Bengaluru - India 🇮🇳 | Cluj-Napoca - Romania 🇷🇴 | Blumenau - Brazil 🇧🇷

## Como se candidatar

Please send an email with your CV to [scout@mindera.com](mailto:scout@mindera.com)

## Tempo médio de feedbacks

We normally respond within a week, our max is 14 days.

## Labels

- Pleno
- Remoto
- Sênior

**Comment by letiveiga** [comment]
You can check in our website too: https://mindera.com/jobs?roles=2

**Comment by carolinaacc** [comment]
Check out the animated version of our handbook on our YouTube channel: https://youtu.be/7teByAHNp7U

**Comment by letiveiga** [comment]
You can check in our website too: https://mindera.com/jobs?roles=2
