### ISSUE TITLE
[Porto] Experienced Backend Software Engineer - .NET na Mindera

### ISSUE THREAD

**Issue by letiveiga** [backend-pt/vagas#87]
## Descrição da vaga

Here at Mindera, we are continuously developing a fantastic team, and would love it for you to join us. As a Microsoft .NET technology stack expert you’ll be part of the development of the core applications

We’re looking for experienced developers who have the appetite for solving complex and interesting problems. Your focus is to develop with high standards while being a good team player with expertise working as part of Agile teams and hands-on experience in practising Scrum, XP and Kanban.

National and international expected traveling time varies according to project/client and organisational needs: 0%-15% estimated.

## Local

Remote or Office or Hybrid, your choice! Our offices are in Porto, Aveiro and Coimbra.

## Benefícios

- Health Insurance, because health comes first
- Flexible working hours
- Open holidays, take the time you need for yourself
- Profit distribution for everyone
- Mindera Annual Trip, Sports, and sharing groups to connect and have fun!
- Training & conferences, create your own training plan
- Child Care vouchers

#### Diferenciais

- Choose Laptop & Peripherals that best suit your needs
- Hotspot with unlimited usage (PT), for work or Netflix ;)
- We have amazing offices in Porto, Aveiro, and Coimbra if you want to physically connect with minders. Remote is also an option.
- At the offices, we have a wide range of snacks to keep you fed and healthy
- Partnerships with local businesses

## Requisitos

- Web development using ASP.NET MVC, or C# or .NET Core 3.1 and above
- Usage of SQL and no SQL databases
- Hands on experience writing unit and integration tests
- Strong design capabilities, following SOLID principles using C#
- Working on solutions hosted in cloud environments (Azure, AWS, or CGP)
- Implementing and maintaining CI/CD pipelines
- Experience with Git
- Experience with serverless is a plus
- Pair programming
- Understanding of Behaviour-driven development and domain-driven design
- Helping your team to deliver at high velocity
- Practice and promote Agile practices

## Contratação

Full-time

## Nossa empresa

At Mindera we use technology to build products we are proud of, with people we love 💛

Software Engineering Applications, including Web and Mobile, are at the core of what we do at Mindera 💻

We partner with our clients, to understand their products and deliver high-performance, resilient, and scalable software systems that create an impact on their users and businesses across the world 🌐

You get to work with a bunch of great people, where the whole team owns the project together 🚀

Our culture reflects our lean and self-management attitude. We encourage our colleagues to take risks, make decisions, work in a collaborative way and talk to everyone to enhance communication 🧭

We are proud of our work and we love to learn all and everything while navigating through an Agile, Lean and collaborative environment ⭐

Check out our [Blog](http://mindera.com/blog) and our [Handbook](http://bit.ly/MinderaHandbook)!

Our offices are located: Porto, Aveiro, Coimbra - Portugal 🇵🇹 | Leicester - UK 🇬🇧 | San Diego, San Francisco - USA 🇺🇸 | Chennai, Bengaluru - India 🇮🇳 | Cluj-Napoca - Romania 🇷🇴 | Blumenau - Brazil 🇧🇷

## Como se candidatar

Please send an email with your CV to [scout@mindera.com](mailto:scout@mindera.com)

## Tempo médio de feedbacks

We normally respond within a week, our max is 14 days.

## Labels

- Mid
- Remote
- Senior

**Comment by carolinaacc** [comment]
Check out the animated version of our handbook on our YouTube channel: https://youtu.be/7teByAHNp7U

**Comment by letiveiga** [comment]
Check JB on our website: https://apply.workable.com/minderacraft/j/6D37238F96/
