### ISSUE TITLE
[Cidade] Back-end Developer na NOME DA EMPRESA

### ISSUE THREAD

**Issue by BeatrizCBotelho** [backend-pt/vagas#99]
## Descrição da vaga

Projeto bazinga em NodeJS, etc.

## Local

Remoto ou Escritório, cidade do Porto, Portugal

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

#### Diferenciais

- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node
- 2 anos de experiência com mongodb e express

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- projetos opensource

## Contratação

RV a combinar (diária ou por hora)

## Nossa empresa

Aqui na Corporação ACME somos líderes em...

## Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

#### Alocação
- Alocado
- Remoto
- Presencial
- Híbrido

#### Regime
- Contrato
- RV
- Estágio
- Freela

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

#### Período
- Full time
- Part time
- Projeto

**Comment by Marcos-vvc** [comment]
Os emails para contato não estão funcionando.

**Comment by guibranco** [comment]
@Marcos-vvc esse é só o template para vagas, não é um anuncio real, aparentemente a @BeatrizCBotelho não colocou os dados da vaga. Issue encerrada.
